### ISSUE TITLE
怎麼輸入ID & Key

### ISSUE THREAD

**Issue by reddratred** [whyliam/whyliam.workflows.youdao#103]
不好意思，我不是程序員專業，想請教大家一下，我已經註冊了有道智雲但卻沒找著 ID & Key 
請問大家這部分在哪個頁面呢？

感謝
![Uploading Screen Shot 2021-07-24 at 1.41.10 PM.png…]()

**Comment by fengqiangzhao** [comment]
这样设置的，请看图片
https://tva1.sinaimg.cn/large/008i3skNly1gw6ys0uzyzj30rs0e7js4.jpg
