### ISSUE TITLE
双击快速翻译改如何设置呢？

### ISSUE THREAD

**Issue by awakeljw** [whyliam/whyliam.workflows.youdao#104]
双击快速翻译改如何设置呢？

**Comment by Yefee** [comment]
It seems no longer working on Monterey.

**Comment by rainplus** [comment]
> 

I'm sorry to hear that

**Comment by rainplus** [comment]
> It seems no longer working on Monterey.
I'm sorry to hear that

**Comment by rainplus** [comment]
> It seems no longer working on Monterey.

I'm sorry to hear that

**Comment by whyliam** [comment]
![image](https://user-images.githubusercontent.com/3387850/162724407-0df62147-ad8d-4dc5-843f-f50f713d249d.png)
