### ISSUE TITLE
Monterey 12.3下无法使用

### ISSUE THREAD

**Issue by zilchzz** [whyliam/whyliam.workflows.youdao#107]
据说是因为macOS Monterey 12.3移除了python2导致alfred下很多workflow无法使用。
目前的情况是，alfred输出框输入yd hello后，会显示"正在获取中"，然后立马出现 search goole for 'yd hello'。

**Comment by zhugexiaobo** [comment]
简单升级了一下 [alfred-workflow-py3](https://github.com/NorthIsUp/alfred-workflow-py3)，有需要可直接使用 MR #108

**Comment by tangkunyin** [comment]
@zilchzz 装了python2，环境正常也不能用！现在有其他解决方式吗？

**Comment by zilchzz** [comment]
> 

我换了一个有道的workflow，作者是wensonsmith的。

**Comment by whyliam** [comment]
已经支持
