### ISSUE TITLE
sentry.io 不可用

### ISSUE THREAD

**Issue by wteng** [whyliam/whyliam.workflows.youdao#109]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/5444252/161891201-c6fd6384-ef9f-4408-97e4-6dba2fea6495.png">

**Comment by whyliam** [comment]
![image](https://user-images.githubusercontent.com/3387850/162724556-fcfc4f43-c122-48db-b2d8-dfca12ae6796.png)

把sentry改成false吧
