### ISSUE TITLE
新版本不兼容alfred v3.8.6

### ISSUE THREAD

**Issue by HoChou** [whyliam/whyliam.workflows.youdao#111]
![image](https://user-images.githubusercontent.com/10461229/163365326-dbc49182-64fd-4950-bf51-24d1c8afa743.png)

**Comment by whyliam** [comment]
https://github.com/whyliam/whyliam.workflows.youdao/releases/tag/2.2.5
你先使用旧版本吧，新版本不在向下兼容

**Comment by charlielin** [comment]
但是旧版本好像不支持 Python3？

**Comment by charlielin** [comment]
> 但是旧版本好像不支持 Python3？

暂时是解决了，使用 alfred workflow 的 debug 功能修改 '/usr/bin/python' 为 pyenv 安装的python2 路径。
