### ISSUE TITLE
Mac 13下无法使用

### ISSUE THREAD

**Issue by gulangyushaonian** [whyliam/whyliam.workflows.youdao#115]
Mac 13下无法使用，如下图
<img width="559" alt="Snipaste_2022-08-12_10-25-19" src="https://user-images.githubusercontent.com/30430387/184273566-e7103439-a733-4262-88d0-02c66449b388.png">

**Comment by dourgulf** [comment]
同问

**Comment by yjxaigithub** [comment]
同问

**Comment by yjxaigithub** [comment]
我发现解决办法了，终端运行xcode-select --install，等它安装完就可以了
