### ISSUE TITLE
翻译频率受限

### ISSUE THREAD

**Issue by xuechengwei** [whyliam/whyliam.workflows.youdao#118]
应该改为输入完成后再调用翻译接口，而不是输入一个字符就翻译一次
![Untitled1](https://user-images.githubusercontent.com/1737662/232954813-3dfbede0-fc05-4bcd-b180-fcfa5adac113.gif)

**Comment by abinnq** [comment]
在其他作者上面fork 了一份，增加了查询间隔设置，可以试试看
https://github.com/abinnq/YoudaoTranslator/releases/tag/3.1.1
