### ISSUE TITLE
MacOS14.3 选中单词之后调用翻译，不能自动翻译对应单词，需要重新复制粘贴

### ISSUE THREAD

**Issue by YarnYang** [whyliam/whyliam.workflows.youdao#124]
选中单词之后调用翻译，不能自动翻译对应单词，需要重新复制粘贴

![image](https://github.com/whyliam/whyliam.workflows.youdao/assets/26480120/00a22b71-f332-4699-ab33-8cb69d04c5e2)
如上图，选中test之后双击翻译，但是翻译框里没有test这个单词，需要重新把test复制粘贴进去才能翻译

**Comment by geekeryy** [comment]
1. 关闭alfred
2. 终端输入：tccutil reset All com.runningwithcrayons.Alfred 
3. 重新打开alfred，按要求重新赋予权限即可
https://www.alfredapp.com/help/getting-started/permissions/#integration
