### ISSUE TITLE
翻译返回结果变的只有一条了

### ISSUE THREAD

**Issue by ChenLeoXX** [whyliam/whyliam.workflows.youdao#125]
有人遇到吗

**Comment by paddy-w** [comment]
感觉是有道的 api 变了

**Comment by williambao** [comment]
同样

**Comment by VWagen1989** [comment]
+1

**Comment by VWagen1989** [comment]
看了下[有道 API ](https://ai.youdao.com/DOCSIRMA/html/trans/api/wbfy/index.html#:~:text=%E4%B8%AD%E8%8B%B1%E4%BA%92%E8%AF%91-,%E8%BE%93%E5%87%BA%E7%BB%93%E6%9E%9C,-%E8%BF%94%E5%9B%9E%E7%9A%84%E7%BB%93%E6%9E%9C)返回的结果，确实改变了。从当前 workflow 的代码看，以前那些翻译条目都在一个叫 "basic" 的条目下面。现在已经没有了。我注意到有个 "webdict" 的条目。发了个请求得到了一个 html 响应。里面正有我们需要的那些翻译结果。所以我搞了个临时方案，改了一下这个 workflow 实际调用的 "index.js" 脚本来适配新的 API。暂时解决了。。

新的脚本在这里（github 不能发 .js 后缀的文件，所以我加了个 .txt 后缀。各位下载之后自己去掉 .txt 后缀再用吧）：
[index.js.txt](https://github.com/whyliam/whyliam.workflows.youdao/files/15369755/index.js.txt)

具体操作流程如下：
* 没有安装 nodejs 的先在自己电脑里安装 [node](https://formulae.brew.sh/formula/node)。`brew install node`
* 然后用 npm 安装这个依赖：cheerio（为了方便解析 html 内容，就装了这个依赖）。`npm install cheerio`
* 接下来，定位到 workflow 的文件夹，并替换掉 index.js 文件。如图：
<img width="454" alt="image" src="https://github.com/whyliam/whyliam.workflows.youdao/assets/111744549/0451609b-b4bb-460d-ac22-9572c3c109d5">
<img width="794" alt="image" src="https://github.com/whyliam/whyliam.workflows.youdao/assets/111744549/e1411598-5f62-4b30-af3c-f0c7eb33bf08">

* 最后，修改一下脚本运行的命令，改为本机 nodejs（以前用的 txiki，引入依赖有点麻烦，所以该用 nodejs）。如图：
<img width="637" alt="image" src="https://github.com/whyliam/whyliam.workflows.youdao/assets/111744549/26fa2583-79d5-47b4-9a83-f7ce7913af4a">
<img width="969" alt="image" src="https://github.com/whyliam/whyliam.workflows.youdao/assets/111744549/ab2aade8-5d2c-4a9f-bf4d-b1bbe7191914">

大功告成！祝玩得开心！

<img width="723" alt="image" src="https://github.com/whyliam/whyliam.workflows.youdao/assets/111744549/75239780-159a-4146-802d-fe23ee9ac940">
<img width="699" alt="image" src="https://github.com/whyliam/whyliam.workflows.youdao/assets/111744549/df22f97d-69a1-4c4b-b4c9-f553cd7a804b">

**Comment by YonkaFang** [comment]
> 看了下[有道 API ](https://ai.youdao.com/DOCSIRMA/html/trans/api/wbfy/index.html#:~:text=%E4%B8%AD%E8%8B%B1%E4%BA%92%E8%AF%91-,%E8%BE%93%E5%87%BA%E7%BB%93%E6%9E%9C,-%E8%BF%94%E5%9B%9E%E7%9A%84%E7%BB%93%E6%9E%9C)返回的结果，确实改变了。从当前 workflow 的代码看，以前那些翻译条目都在一个叫 "basic" 的条目下面。现在已经没有了。我注意到有个 "webdict" 的条目。发了个请求得到了一个 html 响应。里面正有我们需要的那些翻译结果。所以我搞了个临时方案，改了一下这个 workflow 实际调用的 "index.js" 脚本来适配新的 API。暂时解决了。。
> 
> 新的脚本在这里（github 不能发 .js 后缀的文件，所以我加了个 .txt 后缀。各位下载之后自己去掉 .txt 后缀再用吧）： [index.js.txt](https://github.com/whyliam/whyliam.workflows.youdao/files/15369755/index.js.txt)
> 
> 具体操作流程如下：
> 
> * 没有安装 nodejs 的先在自己电脑里安装 [node](https://formulae.brew.sh/formula/node)。`brew install node`
> * 然后用 npm 安装这个依赖：cheerio（为了方便解析 html 内容，就装了这个依赖）。`npm install cheerio`
> * 接下来，定位到 workflow 的文件夹，并替换掉 index.js 文件。如图：
> 
> <img alt="image" width="454" src="https://private-user-images.githubusercontent.com/111744549/331879111-0451609b-b4bb-460d-ac22-9572c3c109d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDA5MTQsIm5iZiI6MTcxNjMwMDYxNCwicGF0aCI6Ii8xMTE3NDQ1NDkvMzMxODc5MTExLTA0NTE2MDliLWI0YmItNDYwZC1hYzIyLTk1NzJjM2MxMDlkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxNDEwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTQzNzJkOGY3ZjM1MTkyYjE0MGJlYjYxOTZkOTNiMzM1Y2U2ZmY4ZTQ2YjNjMGJiYTNkOGEyNTEwOTRkNWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8BdUNX6Mu35kBWDEU6eqZB0smOX_c9YAff0YwTA4Ev8"> <img alt="image" width="794" src="https://private-user-images.githubusercontent.com/111744549/331879219-e1411598-5f62-4b30-af3c-f0c7eb33bf08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDA5MTQsIm5iZiI6MTcxNjMwMDYxNCwicGF0aCI6Ii8xMTE3NDQ1NDkvMzMxODc5MjE5LWUxNDExNTk4LTVmNjItNGIzMC1hZjNjLWYwYzdlYjMzYmYwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxNDEwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmNlYjAzNmY1ZmI0YmFmZjFlYWU1NDcyNDgzYjM3MjIwM2FjMzRjMDZkOTc4Y2Q3ODE5OGUzMGU5ZjhmYTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x0GXWivVW9NQ1G8miFHngJ1sdUBp_iUo9iqtDxl8bj4">
> * 最后，修改一下脚本运行的命令，改为本机 nodejs（以前用的 txiki，引入依赖有点麻烦，所以改用 nodejs）。如图：
> 
> <img alt="image" width="637" src="https://private-user-images.githubusercontent.com/111744549/331879302-26fa2583-79d5-47b4-9a83-f7ce7913af4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDA5MTQsIm5iZiI6MTcxNjMwMDYxNCwicGF0aCI6Ii8xMTE3NDQ1NDkvMzMxODc5MzAyLTI2ZmEyNTgzLTc5ZDUtNDdiNC05YTgzLWY3Y2U3OTEzYWY0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxNDEwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGNjYjUzMzhlZGRmNWQxM2Y3YmQwZDYzYzFmYWY1NmFiOGUzMmQxMDJhMDIzMGNlYjRiMWE0YzdjYTE4MTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DviE_eSOKxTdmpw9tughOJs7TiJne8T699xTFWTRb88"> <img alt="image" width="969" src="https://private-user-images.githubusercontent.com/111744549/331879398-ab2aade8-5d2c-4a9f-bf4d-b1bbe7191914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDA5MTQsIm5iZiI6MTcxNjMwMDYxNCwicGF0aCI6Ii8xMTE3NDQ1NDkvMzMxODc5Mzk4LWFiMmFhZGU4LTVkMmMtNGE5Zi1iZjRkLWIxYmJlNzE5MTkxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxNDEwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmRkOWY0ZTI1YTJkOTAyNDVkOWRmYWQ2ZGEzN2IyYTg4Y2FkOWY4YjRkZjI3ZjE4ZTVkMzhiMmZkOTM1N2M3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RrJ-4vts4OJy2k5d2choi6l4heniQe3rMw46h9GB4UY">
> 大功告成！祝玩得开心！
> 
> <img alt="image" width="723" src="https://private-user-images.githubusercontent.com/111744549/331879740-75239780-159a-4146-802d-fe23ee9ac940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDA5MTQsIm5iZiI6MTcxNjMwMDYxNCwicGF0aCI6Ii8xMTE3NDQ1NDkvMzMxODc5NzQwLTc1MjM5NzgwLTE1OWEtNDE0Ni04MDJkLWZlMjNlZTlhYzk0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxNDEwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGFjNTY3NjgzMWJkMzdjYjFiZjA2OTQ0ZDUzNzUxZjM0MDAyN2JjODQyYmY5YzYzMjg4OWQ5ZGZjYjM2N2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eY6eXBdEFaFjkiVQnoo8wfMxfykZRD7HdjMuPSJpalY"> <img alt="image" width="699" src="https://private-user-images.githubusercontent.com/111744549/331879799-df22f97d-69a1-4c4b-b4c9-f553cd7a804b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDA5MTQsIm5iZiI6MTcxNjMwMDYxNCwicGF0aCI6Ii8xMTE3NDQ1NDkvMzMxODc5Nzk5LWRmMjJmOTdkLTY5YTEtNGM0Yi1iNGM5LWY1NTNjZDdhODA0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxNDEwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTgzNGFkOTNkODVhOThjMGIyYmE4ZmU1Yzk4YWVkZWVjNzRkZmZhNGMxNTQ0NGM4MDI3ZTFmZTM5NTQ5YzczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OgfKBiHEMpwtWGk9PYes9rHB47Zv8TeaZ935Vygl0vM">

感谢，方便提个PR吗？

**Comment by VWagen1989** [comment]
> @VWagen1989
> 
> 感谢，方便提个PR吗？

本来想提 PR 的，但是没看到这个项目里哪个文件生成的 index.js... ¯\_(ツ)_/¯

**Comment by YonkaFang** [comment]
> > @VWagen1989
> > 感谢，方便提个PR吗？
> 
> 本来想提 PR 的，但是没看到这个项目里哪个文件生成的 index.js... ¯\_(ツ)_/¯

仔细看了下，你的图好像是wenson那个项目的workflow修改 😂

**Comment by VWagen1989** [comment]
> > > @VWagen1989
> > > 感谢，方便提个PR吗？
> > 
> > 
> > 本来想提 PR 的，但是没看到这个项目里哪个文件生成的 index.js... ¯_(ツ)_/¯
> 
> 仔细看了下，你的图好像是wenson那个项目的workflow修改 😂

还真是，搞混了。。:sweat_smile: 有空我再提个 PR 吧。不过我的实现方式太过 tricky，看看大佬接不接收吧。

**Comment by kennydiff** [comment]
大佬好像放弃这个项目了，2年没更了~

**Comment by kennydiff** [comment]
> 看了下[有道 API ](https://ai.youdao.com/DOCSIRMA/html/trans/api/wbfy/index.html#:~:text=%E4%B8%AD%E8%8B%B1%E4%BA%92%E8%AF%91-,%E8%BE%93%E5%87%BA%E7%BB%93%E6%9E%9C,-%E8%BF%94%E5%9B%9E%E7%9A%84%E7%BB%93%E6%9E%9C)返回的结果，确实改变了。从当前 workflow 的代码看，以前那些翻译条目都在一个叫 "basic" 的条目下面。现在已经没有了。我注意到有个 "webdict" 的条目。发了个请求得到了一个 html 响应。里面正有我们需要的那些翻译结果。所以我搞了个临时方案，改了一下这个 workflow 实际调用的 "index.js" 脚本来适配新的 API。暂时解决了。。
> 
> 新的脚本在这里（github 不能发 .js 后缀的文件，所以我加了个 .txt 后缀。各位下载之后自己去掉 .txt 后缀再用吧）： [index.js.txt](https://github.com/whyliam/whyliam.workflows.youdao/files/15369755/index.js.txt)
> 
> 具体操作流程如下：
> 
> * 没有安装 nodejs 的先在自己电脑里安装 [node](https://formulae.brew.sh/formula/node)。`brew install node`
> * 然后用 npm 安装这个依赖：cheerio（为了方便解析 html 内容，就装了这个依赖）。`npm install cheerio`
> * 接下来，定位到 workflow 的文件夹，并替换掉 index.js 文件。如图：
> 
> <img alt="image" width="454" src="https://private-user-images.githubusercontent.com/111744549/331879111-0451609b-b4bb-460d-ac22-9572c3c109d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTYyNDcsIm5iZiI6MTcxNzY5NTk0NywicGF0aCI6Ii8xMTE3NDQ1NDkvMzMxODc5MTExLTA0NTE2MDliLWI0YmItNDYwZC1hYzIyLTk1NzJjM2MxMDlkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxNzQ1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWNkZmUzZWQwMjZjMjhlMzg1ZjA5ZWNjYTMwNmJiMzk3ODM1MzAwOGYxMGY3NDIxOGE4Y2QwZjhjMTY5NjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HDqzjndr1u9l4vh5SrWUFOLG7iUQWVwR6aSxZmYwqSI"> <img alt="image" width="794" src="https://private-user-images.githubusercontent.com/111744549/331879219-e1411598-5f62-4b30-af3c-f0c7eb33bf08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTYyNDcsIm5iZiI6MTcxNzY5NTk0NywicGF0aCI6Ii8xMTE3NDQ1NDkvMzMxODc5MjE5LWUxNDExNTk4LTVmNjItNGIzMC1hZjNjLWYwYzdlYjMzYmYwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxNzQ1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTgxMzVlMDRkYjlkMzRlNmU3OWQxN2VlMWRlMTYxYWNjYjQ5ODI5OTNiZDBjMjRkYjZjZmNlYWI3MjdlZDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eAc_G78nWGxxxs74BtX29hEQIVM74ruAPafe5kqWXMA">
> * 最后，修改一下脚本运行的命令，改为本机 nodejs（以前用的 txiki，引入依赖有点麻烦，所以改用 nodejs）。如图：
> 
> <img alt="image" width="637" src="https://private-user-images.githubusercontent.com/111744549/331879302-26fa2583-79d5-47b4-9a83-f7ce7913af4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTYyNDcsIm5iZiI6MTcxNzY5NTk0NywicGF0aCI6Ii8xMTE3NDQ1NDkvMzMxODc5MzAyLTI2ZmEyNTgzLTc5ZDUtNDdiNC05YTgzLWY3Y2U3OTEzYWY0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxNzQ1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTExZTg5N2I1OTVhZDNhY2Y3MjQzMjcyNjI2MDJjZDcyYWI4MTNhNjFlNDNmMTk3ZGM1YWJjMzEyYjdlMzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mb3YKghNdqpEAi67hNakxNzYh6qMSEEwUD6OAK0pGzQ"> <img alt="image" width="969" src="https://private-user-images.githubusercontent.com/111744549/331879398-ab2aade8-5d2c-4a9f-bf4d-b1bbe7191914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTYyNDcsIm5iZiI6MTcxNzY5NTk0NywicGF0aCI6Ii8xMTE3NDQ1NDkvMzMxODc5Mzk4LWFiMmFhZGU4LTVkMmMtNGE5Zi1iZjRkLWIxYmJlNzE5MTkxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxNzQ1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWNjMmI1ODAzODg4NjAwYmZkZTM3OGI2MTZiODA1NWM1ZmQzYzcyOWQwNDljODdjODBmNDNlOTkwMjFlYzJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F_E3zQ3tOPxGPXIXmNUxYz6DGpkgg2PdxmKtu1cK6l4">
> 大功告成！祝玩得开心！
> 
> <img alt="image" width="723" src="https://private-user-images.githubusercontent.com/111744549/331879740-75239780-159a-4146-802d-fe23ee9ac940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTYyNDcsIm5iZiI6MTcxNzY5NTk0NywicGF0aCI6Ii8xMTE3NDQ1NDkvMzMxODc5NzQwLTc1MjM5NzgwLTE1OWEtNDE0Ni04MDJkLWZlMjNlZTlhYzk0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxNzQ1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjlhNWM0OGE2MmUzNDBiNjgzM2ZkODRlODM0YjJiYmFkOTdjNDlmOTUyYzc3ZjUyMDhhMGFkNDJiNmNhYTQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.52H-jHFxMs0JXkGjL6jGfBhD2l0boHjk4509rXo3NjQ"> <img alt="image" width="699" src="https://private-user-images.githubusercontent.com/111744549/331879799-df22f97d-69a1-4c4b-b4c9-f553cd7a804b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTYyNDcsIm5iZiI6MTcxNzY5NTk0NywicGF0aCI6Ii8xMTE3NDQ1NDkvMzMxODc5Nzk5LWRmMjJmOTdkLTY5YTEtNGM0Yi1iNGM5LWY1NTNjZDdhODA0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxNzQ1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDIwMTIyNDU1YjAzNjcxMjBjNTAyYmUxODJlYzljYzU1ODkxMWYwNWQ2MjY4ZjllY2ZmMDk1NTNlNDM2NGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Poxa7zEZXkl1dPWk_zSXU6r8osvygZquuMgDmLgrcOw">

要不你fork 一个repo吧 😊

**Comment by kennydiff** [comment]
> > > > @VWagen1989
> > > > 感谢，方便提个PR吗？
> > > 
> > > 
> > > 本来想提 PR 的，但是没看到这个项目里哪个文件生成的 index.js... ¯_(ツ)_/¯
> > 
> > 
> > 仔细看了下，你的图好像是wenson那个项目的workflow修改 😂
> 
> 还真是，搞混了。。😅 有空我再提个 PR 吧。不过我的实现方式太过 tricky，看看大佬接不接收吧。

要不你fork 一个repo吧 😊~~~ 一定`Star`

**Comment by zhangbw409** [comment]
@VWagen1989 大佬，修改为这种方式后，只能翻译单词，句子好像翻译不了。
使用的是这个插件： https://github.com/wensonsmith/YoudaoTranslator
<img width="980" alt="image" src="https://github.com/whyliam/whyliam.workflows.youdao/assets/50818583/254275fb-ae20-4881-ac99-0cd186dff68d">

<img width="1043" alt="image" src="https://github.com/whyliam/whyliam.workflows.youdao/assets/50818583/5cd74c3b-00ad-43c4-913f-2812c8e5c128">

**Comment by silencewwt** [comment]
继续歪个楼，我用的也是 [wensonsmith/YoudaoTranslator](https://github.com/wensonsmith/YoudaoTranslator) 的项目，这个问题也困扰了我很久，端午假期终于有时间下定决心要解决这个问题了。

@VWagen1989 感谢大佬的代码，我“复用”了一下 https://github.com/wensonsmith/YoudaoTranslator/pull/153

@zhangbw409 可以试下这个还热乎的临时修复版本 https://github.com/silencewwt/YoudaoTranslator/releases/tag/3.1.1

**Comment by zhangbw409** [comment]
@silencewwt 大佬，这个修复版本好像只能翻译单词，句子翻译不了。

**Comment by whyliam** [comment]
有道下线了字典 API，原来的方式用不了了，换了个数据获取方式 https://github.com/whyliam/whyliam.workflows.youdao/releases/tag/4.0.0
