### ISSUE TITLE
网页打不开，快捷键取词不管用

### ISSUE THREAD

**Issue by keke521** [whyliam/whyliam.workflows.youdao#71]

**Comment by whyliam** [comment]
![](https://camo.githubusercontent.com/439cd55fdddc6e8dbb2fdf5b7e2db981baaca0a7/687474703a2f2f7777322e73696e61696d672e636e2f6c617267652f303036744e62527767793166656e6f36707a6178646a333161363070306a736c2e6a7067)

有按照这个设置吗？

**Comment by keke521** [comment]
有，快捷键可以打开 alfred 并显示 “yd“ 但是后面没有内容！另外，用网页打开没反应！我是 mac 系统10.14.4 。 alfred3.6.2
----- 原始邮件 -----
发件人：whyliam <notifications@github.com>
收件人："whyliam/whyliam.workflows.youdao" <whyliam.workflows.youdao@noreply.github.com>
抄送人：Someone <xueyingkuang521@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[whyliam/whyliam.workflows.youdao]_网页打不开，快捷键取词不管用_(#71)
日期：2019年04月03日 16点40分



有按照这个设置吗？



&mdash;

**Comment by keke521** [comment]
![image](https://user-images.githubusercontent.com/24793262/55465572-fbd4f500-562f-11e9-9171-07a8eefabc75.png)

**Comment by whyliam** [comment]
先选择要翻译的内容，在 双击。

网页打不开是指 同时按下 Ctrl 和 回车 不行吗？

其他的快捷键可以使用吗？

**Comment by keke521** [comment]
😂我知道先选择内容，也不行！发音快捷键可以，直接 enter 复制也可以！其他的条件有限 没试

**Comment by keke521** [comment]
刚试了commend+enter 打印也不行

**Comment by whyliam** [comment]
你用的是最新的版本吗？
https://github.com/whyliam/whyliam.workflows.youdao/releases/tag/2.2.2

我这里没有什么问题:cry:

**Comment by keke521** [comment]
![image](https://user-images.githubusercontent.com/24793262/55467256-78b59e00-5633-11e9-9990-2443cc3bf3bf.png)

**Comment by keke521** [comment]
只不过刚导入的时候 alfred 报了个 https://www.alfredapp.com/help/troubleshooting/incompatible-python-workflow-library/ 
我按照这个 fix 了一下 不知是不是这个导致的

**Comment by whyliam** [comment]
![WX20190403-171636](https://user-images.githubusercontent.com/3387850/55475199-d652e600-5645-11e9-9d75-3a73b8d6a1e0.png)

看一下有报什么错误吗？

**Comment by whyliam** [comment]
你的Alfred的版本是2还是3？

**Comment by keke521** [comment]
alfred 版本3.6.2   翻译正常没报错！control+enter没有 log

**Comment by jizhizhu** [comment]
快捷键取词可是尝试在系统偏好设置-安全性与隐私-隐私-辅助功能里把alfred勾上，我默认是没勾的，勾上之后好了

**Comment by whyliam** [comment]
@jizhizhu Thanks 👍

**Comment by w15971597** [comment]
> 快捷键取词可以尝试在系统偏好设置-安全性与隐私-隐私-辅助功能里把alfred勾上，我默认是没勾的，勾上之后好了

试了下，我默认是勾上了，取消勾选，再勾选，Selection in macOS才生效
