### ISSUE TITLE
 v2.2.3不支持 Alfred 3.6.1[910]

### ISSUE THREAD

**Issue by GanZhiXiong** [whyliam/whyliam.workflows.youdao#73]
![image](https://user-images.githubusercontent.com/27394631/61574249-7fd3bf80-aaef-11e9-9589-d84691bd1784.png)

**Comment by whyliam** [comment]
已经修复 https://github.com/whyliam/whyliam.workflows.youdao/releases/tag/2.2.3

**Comment by GanZhiXiong** [comment]
OK,Thanks!
