### ISSUE TITLE
同步到词本提示 “帐号出错，临时保存至本地单词本”——有道账号大小写的问题

### ISSUE THREAD

**Issue by JackYum** [whyliam/whyliam.workflows.youdao#77]
有道账号如果用的是网易@163.com邮箱，并且账号中包含了大写字母会导致“帐号出错，临时保存至本地单词本”的问题，邮箱中的字母必须全部转为小写，是否可以将输入“******@163.com”账号统一转成大写？

**Comment by zxmatrix62** [comment]
我现在还有这个问题 - -
