### ISSUE TITLE
双击⌥不能直接翻译选中的词了，无论中或英。

### ISSUE THREAD

**Issue by Deepout** [whyliam/whyliam.workflows.youdao#78]
RT.
Alfred是最新版的，双击⌥只显示一个 yd 空格，不像以前，选中的词直接上屏。
作者可以修复此bug吗？非常感谢！

**Comment by whyliam** [comment]
尝试移除权限后重新添加
https://github.com/whyliam/whyliam.workflows.youdao/issues/75

**Comment by Deepout** [comment]
> 尝试移除权限后重新添加
> #75

感谢，恢复正常！

**Comment by yinshuxun** [comment]
@Deepout @whyliam   你好，我也遇到这个问题，具体是什么权限，我把安全和隐私里隐私中的所有能勾选的选项都勾掉重新选择了，依然不行
