### ISSUE TITLE
使用时，不能翻译，仅显示更新选项

### ISSUE THREAD

**Issue by Elvins** [whyliam/whyliam.workflows.youdao#80]
使用时，不能翻译，仅显示更新选项
1、马上更新
2、暂不更新

**Comment by whyliam** [comment]
上个版本有个bug导致自动更新失败，请先手动安装最新版本。

**Comment by Elvins** [comment]
> 上个版本有个bug导致自动更新失败，请先手动安装最新版本。

我现在用的版本是2.2.3，如果要升级3，我目前的alfred版本还不是最新版

**Comment by whyliam** [comment]
@Elvins 试一下这个版本 https://github.com/whyliam/whyliam.workflows.youdao/releases/download/2.2.4/whyliam.workflows.youdao.alfred3workflow

**Comment by Elvins** [comment]
> @Elvins 试一下这个版本 https://github.com/whyliam/whyliam.workflows.youdao/releases/download/2.2.4/whyliam.workflows.youdao.alfred3workflow

谢谢，我已经更新到alfred 4了
