### ISSUE TITLE
倒入alfred 提示不能用

### ISSUE THREAD

**Issue by wonsaign** [whyliam/whyliam.workflows.youdao#81]
刚刚更新的yd插件，提示不能用，好在我保留了之前版本的，现在又用回以前的版本了

**Comment by whyliam** [comment]
本来不想维护Alfred3的，我重新打包了Alfred3的版本。
https://github.com/whyliam/whyliam.workflows.youdao/releases/download/2.2.4/whyliam.workflows.youdao.alfred3workflow
