### ISSUE TITLE
怎么前几天发布的是3.0.0，现在不见了？

### ISSUE THREAD

**Issue by dxvgef** [whyliam/whyliam.workflows.youdao#82]
我记得前几天发布过3.0.0，我都已经安装了，现在怎么找不到了，只剩2.x了？

**Comment by whyliam** [comment]
原来的3.0.0只支持Alfred4，很多人反馈他们使用的还是Alfred3。
所以将3.0.0调整为了2.2.4，同时兼容到Alfred3。

**Comment by dxvgef** [comment]
那现在最新的是2.2.4还是我之前下载的3.0.0？还是2.2.4就是原来的3.0.0？

**Comment by whyliam** [comment]
@dxvgef 使用2.2.4吧，虽然两个代码基本是一样的（只是做了兼容Alfred3）。但是如果涉及后续的升级版本，2.2.4可以自动升级，3.0.0的可能就收不到升级提示了

**Comment by dxvgef** [comment]
好的，谢谢
