### ISSUE TITLE
“选中文字 双击Command进行翻译”功能不可用

### ISSUE THREAD

**Issue by meltedmetal** [whyliam/whyliam.workflows.youdao#83]
非常感谢分析此workflow。赞！
今天安装2.2.3版本后发现“选中文字 双击Command进行翻译”功能不可用。
无论是双击 command 还是 双击 option。
是需要什么设置吗？还是不兼容的问题。

MacOS版本 ： Catalina  10.15.1
whyliam.workflows.youdao版本   v2.2.3
Alfred 版本： v4.0.7

**Comment by whyliam** [comment]
https://github.com/whyliam/whyliam.workflows.youdao/issues/75

**Comment by whyliam** [comment]
同时建议使用2.2.4版本，2.2.3存在不可以自动升级的BUG

**Comment by meltedmetal** [comment]
@whyliam 谢谢。 按照 #75 解决了。
