### ISSUE TITLE
更新3.00和2.2.4后无法翻译

### ISSUE THREAD

**Issue by iSteveyang** [whyliam/whyliam.workflows.youdao#84]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/20753221/70913803-af143b80-2051-11ea-914f-d0ef5f85ff38.png">

Alfred 4.0.6
macOS 10.15.2
之前自动更新3.0之后就不行了
一直这样
今天更新2.2.4，并且加了智能云api后还是不行

**Comment by whyliam** [comment]
![image](https://user-images.githubusercontent.com/3387850/71074018-8066a400-21bc-11ea-8670-394b92987483.png)
点击右上角的debug按钮，下方有什么错误提示吗？

**Comment by iSteveyang** [comment]
> [20:32:00.184] Youdao[Script Filter] Queuing argument 'hello'
> [20:32:00.402] Youdao[Script Filter] Script with argv '(null)' finished
> [20:32:00.404] ERROR: Youdao[Script Filter] Code 1: Traceback (most recent call last):
>   File "youdao.py", line 342, in <module>
>     init_sentry()
>   File "youdao.py", line 70, in init_sentry
>     "https://4d5a5b1f2e68484da9edd9076b86e9b7@sentry.io/1500348")
>   File "/Users/isteveyang/Documents/***Config***/Alfred/Alfred.alfredpreferences/workflows/user.workflow.19BA9C20-F0CF-4D53-91C2-A63F043F2DCD/sentry_sdk/hub.py", line 80, in _init
>     client = Client(*args, **kwargs)  # type: ignore
>   File "/Users/isteveyang/Documents/***Config***/Alfred/Alfred.alfredpreferences/workflows/user.workflow.19BA9C20-F0CF-4D53-91C2-A63F043F2DCD/sentry_sdk/client.py", line 80, in __init__
>     self._init_impl()
>   File "/Users/isteveyang/Documents/***Config***/Alfred/Alfred.alfredpreferences/workflows/user.workflow.19BA9C20-F0CF-4D53-91C2-A63F043F2DCD/sentry_sdk/client.py", line 96, in _init_impl
>     self.transport = make_transport(self.options)
>   File "/Users/isteveyang/Documents/***Config***/Alfred/Alfred.alfredpreferences/workflows/user.workflow.19BA9C20-F0CF-4D53-91C2-A63F043F2DCD/sentry_sdk/transport.py", line 261, in make_transport
>     return transport_cls(options)
>   File "/Users/isteveyang/Documents/***Config***/Alfred/Alfred.alfredpreferences/workflows/user.workflow.19BA9C20-F0CF-4D53-91C2-A63F043F2DCD/sentry_sdk/transport.py", line 104, in __init__
>     ca_certs=options["ca_certs"],
>   File "/Users/isteveyang/Documents/***Config***/Alfred/Alfred.alfredpreferences/workflows/user.workflow.19BA9C20-F0CF-4D53-91C2-A63F043F2DCD/sentry_sdk/transport.py", line 194, in _make_pool
>     return urllib3.ProxyManager(proxy, **opts)
>   File "/Users/isteveyang/Documents/***Config***/Alfred/Alfred.alfredpreferences/workflows/user.workflow.19BA9C20-F0CF-4D53-91C2-A63F043F2DCD/urllib3/poolmanager.py", line 420, in __init__
>     raise ProxySchemeUnknown(proxy.scheme)
> urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None

发现是clashX代理的问题，关了就没事，直连和pac都报错，但是不开不行啊，Alfred也没配置过代理。有什么解决办法吗？

**Comment by whyliam** [comment]
https://github.com/whyliam/whyliam.workflows.youdao/issues/64

**Comment by WangZhuangIT** [comment]
yd 你好
翻译的时候提示 马上更新  暂不更新，但是无法翻译了，版本2.2.4

**Comment by iSteveyang** [comment]
> #64

Alfred4配置代理端口https，无法连接，直接关掉了通过代理运行脚本，就行了
