### ISSUE TITLE
提示更新

### ISSUE THREAD

**Issue by WangZhuangIT** [whyliam/whyliam.workflows.youdao#85]
yd 你好
翻译的时候提示 马上更新 / 暂不更新 ，版本2.2.4 ，无法翻译了

**Comment by whyliam** [comment]
现在最新版是 2.2.4 应该不会检测出新的版本。
选择 暂不更新 后，可以进行其他的操作吗？

**Comment by WangZhuangIT** [comment]
马上更新和暂不更新，点哪个都没用，点完之后Alfred的窗口就消失了，在打开翻译的时候，还是提示  马上更新 / 暂不更新

**Comment by whyliam** [comment]
我暂时排查不出原因，可以尝试重新安装2.2.4版本后试一下。（2.2.3版本有上述问题）

**Comment by pyfreyr** [comment]
使用的 2.2.4 版本，今天突然也显示新版本无法使用，之前好好的。

![image](https://user-images.githubusercontent.com/44150955/73604773-128e0480-45d1-11ea-83b8-969b3065e353.png)

![image](https://user-images.githubusercontent.com/44150955/73604771-0a35c980-45d1-11ea-8bfb-b079b534a61c.png)

**Comment by whyliam** [comment]
@pyfreyr 暂不更新存在bug，可以选择马上更新。

由于网络问题和软件限制，可能下载速度比较慢

**Comment by li5454yong** [comment]
![image](https://user-images.githubusercontent.com/11953309/73645786-f367a380-46b2-11ea-97ee-46671df2cd91.png)
选择马上更新之后，等了很久也没什么反应

**Comment by whyliam** [comment]
@li5454yong 打开Alfred的preference看一下是不是有提醒更新。如果还不行的话手动下载一下吧。

https://github.com/whyliam/whyliam.workflows.youdao/releases/download/2.2.5/whyliam.workflows.youdao.alfred3workflow

**Comment by pyfreyr** [comment]
使用最新 v2.2.5  问题解决，感谢！
