### ISSUE TITLE
能不能在搜索结果里显示音标？

### ISSUE THREAD

**Issue by chillyond** [whyliam/whyliam.workflows.youdao#86]
之前用过一个workflow有音标，是否可以加上这个功能呢？

**Comment by whyliam** [comment]
英文词语是有显示音标的

**Comment by love1491** [comment]
hi whyliam, 之前你的workflow是有音标的, 但是最近貌似网易的api更新了, 如果请求参数的from和to是auto, 那么返回结果会缺失basic字段, 导致没有音标和其他更多结果. 我尝试了把from和to改成en, zh-CHS后恢复正常展示. 期待你的更新!
[网易API说明](https://irma.youdao.com/html/%E8%87%AA%E7%84%B6%E8%AF%AD%E8%A8%80%E7%BF%BB%E8%AF%91/API%E6%96%87%E6%A1%A3/%E6%96%87%E6%9C%AC%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1/%E6%96%87%E6%9C%AC%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1-API%E6%96%87%E6%A1%A3.html) 中'当FROM和TO的值有在{zh-CHS, EN}范围外的时候'

**Comment by whyliam** [comment]
已经更新 https://github.com/whyliam/whyliam.workflows.youdao/pull/88

可以下载https://github.com/whyliam/whyliam.workflows.youdao/releases/tag/2.2.5 版本
