### ISSUE TITLE
翻译一整句的时候，按cmd+L翻译的就不是中文了

### ISSUE THREAD

**Issue by nobut** [whyliam/whyliam.workflows.youdao#92]

**Comment by nobut** [comment]
<img width="1182" alt="Screen Shot 2020-02-25 at 1 58 50 PM" src="https://user-images.githubusercontent.com/28843198/75220158-b9814d00-57d9-11ea-9436-505370c34e53.png">

**Comment by nobut** [comment]
就是正常情况下我选中一段翻译，然后按快捷键翻译一行是翻译不下的，然后我按cmd+L这个快捷键会多行显示，但是我猜测多行显示只是复制了，而没有翻译。请问能修改一下吗？

**Comment by whyliam** [comment]
alfred 翻译长句子的效果没有那么好，建议还是使用在线翻译吧
