### ISSUE TITLE
不能翻译了，现在workflow出问题了吗？

### ISSUE THREAD

**Issue by GanZhiXiong** [whyliam/whyliam.workflows.youdao#94]
刚开始显示如下
![image](https://user-images.githubusercontent.com/27394631/76298242-1dd10000-62f4-11ea-847a-c8ad046fd1a4.png)
过了一会显示如下
![image](https://user-images.githubusercontent.com/27394631/76298268-275a6800-62f4-11ea-94c7-b01089e19dc4.png)

也不能翻译了，现在workflow出问题了吗？

**Comment by GanZhiXiong** [comment]
![image](https://user-images.githubusercontent.com/27394631/76604534-d479ee00-6549-11ea-942b-1d65806daf34.png)
上图是日志输出，麻烦您帮忙看下这个问题
谢谢😀

**Comment by whyliam** [comment]
@GanZhiXiong 你先试一下删除后重新安装可不可以，如果不可以我在想想怎么处理。

**Comment by GanZhiXiong** [comment]
我更新到Alfred4.0.9就没有问题了
Thanks😃
