### ISSUE TITLE
双击option不好用

### ISSUE THREAD

**Issue by BaiMingxu1** [whyliam/whyliam.workflows.youdao#98]
为什么我的热键设置跟您的截图上不一样？我设置了双击option虽然弹出来搜索框，可是并没有自动翻译。怎么解决呀？

<img width="450" alt="截屏2020-04-12 13 17 42" src="https://user-images.githubusercontent.com/24521229/79061263-e70a5300-7cc0-11ea-840f-e6b660dd6283.png">

**Comment by BaiMingxu1** [comment]
<img width="450" alt="截屏2020-04-12 13 17 42" src="https://user-images.githubusercontent.com/24521229/79061227-69464780-7cc0-11ea-9f29-4318242de44b.png">

**Comment by whyliam** [comment]
![image](https://user-images.githubusercontent.com/3387850/150293643-bf9044c2-24dc-42b6-98b1-f171a93a686a.png)

首先先重新请求一下权限
