### ISSUE TITLE
无法发音

### ISSUE THREAD

**Issue by lolstudio** [whyliam/whyliam.workflows.youdao#99]
Alfred3 无法发音，是需要创建有道智云应用吗，报错如下：

`[2020-05-22 12:00:02][ERROR: action.script] .
12:00:02 workflow.py:2061 DEBUG    ---------- Youdao (2.2.5) ----------
12:00:02 workflow.py:1468 DEBUG    reading settings from /Users/xxx/Library/Application Support/Alfred 3/Workflow Data/whyliam.workflows.youdao/settings.json
12:00:02 workflow.py:2338 INFO     checking for update ...
12:00:02 background.py:233 DEBUG    [__workflow_update_check] command cached: /Users/xxx/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/whyliam.workflows.youdao/__workflow_update_check.argcache
12:00:02 background.py:237 DEBUG    [__workflow_update_check] passing job to background runner: [u'/usr/bin/python', '/Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.521AC746-55D8-459A-9983-713942197D1D/workflow/background.pyc', u'__workflow_update_check']
.
12:00:02 workflow.py:2061 DEBUG    ---------- Youdao (2.2.5) ----------
12:00:02 background.py:243 DEBUG    [__workflow_update_check] background job started
Open speech channel failed: -76
12:00:02 workflow.py:2254 DEBUG    set last run version: 2.2.5
12:00:02 workflow.py:2103 DEBUG    ---------- finished in 0.136s ----------`

**Comment by wuchuanyu** [comment]
终端执行
`sudo pkill speechsynthesisd say`

**Comment by lolstudio** [comment]
> 终端执行
> `sudo pkill speechsynthesisd say`

无效额：

`[2020-05-29 20:05:47][ERROR: action.script] .
20:05:46 workflow.py:2061 DEBUG    ---------- Youdao (2.2.5) ----------
20:05:46 workflow.py:1468 DEBUG    reading settings from /Users/anchengxing/Library/Application Support/Alfred 3/Workflow Data/whyliam.workflows.youdao/settings.json
20:05:46 workflow.py:2338 INFO     checking for update ...
20:05:46 background.py:233 DEBUG    [__workflow_update_check] command cached: /Users/anchengxing/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/whyliam.workflows.youdao/__workflow_update_check.argcache
20:05:46 background.py:237 DEBUG    [__workflow_update_check] passing job to background runner: [u'/usr/bin/python', '/Users/anchengxing/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.521AC746-55D8-459A-9983-713942197D1D/workflow/background.pyc', u'__workflow_update_check']
.
20:05:47 workflow.py:2061 DEBUG    ---------- Youdao (2.2.5) ----------
20:05:47 background.py:243 DEBUG    [__workflow_update_check] background job started
Open speech channel failed: -76
20:05:47 workflow.py:2254 DEBUG    set last run version: 2.2.5
20:05:47 workflow.py:2103 DEBUG    ---------- finished in 0.133s ----------`

**Comment by dlqnjupt** [comment]
无法发音

**Comment by peipei7k7k** [comment]
> sudo pkill speechsynthesisd say

执行后还是无法发音。

**Comment by whyliam** [comment]
`say --voice='Samantha' Hello  `
看一下有什么报错
